#!/bin/bash
pipeline
{
    agent 
    {
	    label 'Node-1'
    }
    stages
    {
        stage('uptime')
        {
            steps{
                sh 'uptime'
            }
        }
        stage('hostname')
        {
            steps{
                sh 'hostname'
            }
        }
       stage('ip address')
        {
            steps{
                sh 'hostname -I'
            }
        }
        stage('cpu time')
        {
            steps{
                sh 'lscpu'
            }
        }
    }
}
